### ISSUE TITLE
Error: undefined symbol in sodium.node

### ISSUE THREAD

**Issue by clehner** [ssbc/patchwork#14]
I cloned the repo and ran `npm install -d`.
When I run the app I get an error. It seems to be an issue with Electron or the chloride module.
Running `npm run test` in both ssb-keys and chloride directories passes.
I can also require() the referenced `sodium.node` from a nodejs repl without error. Any idea what to do now?
```
$ npm start

> ssb-patchwork@0.0.3 start /usr/local/src/patchwork
> electron .

[28382:0814/073314:ERROR:browser_main_loop.cc(173)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
App threw an error when running [Error: /usr/local/src/patchwork/node_modules/ssb-keys/node_modules/chloride/build/Release/sodium.node: undefined symbol: _ZN2v87Context10GetCurrentEv]
A JavaScript error occured in the browser process
Uncaught Exception:
Error: /usr/local/src/patchwork/node_modules/ssb-keys/node_modules/chloride/build/Release/sodium.node: undefined symbol: _ZN2v87Context10GetCurrentEv
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/src/patchwork/node_modules/ssb-keys/node_modules/chloride/lib/sodium.js:16:15)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
[28382:0814/073315:INFO:audio_manager_pulse.cc(258)] Failed to connect to the context.  Error: Connection refused
```

**Comment by pfraze** [comment]
@clehner what platform are you on?

**Comment by clehner** [comment]
Debian testing (Linux 4.0.0-pf2)

**Comment by pfraze** [comment]
@clehner and what version of node/io?

**Comment by clehner** [comment]
Node v0.10.38

**Comment by pfraze** [comment]
@clehner I'd bet that's the issue. Could you try installing https://github.com/creationix/nvm, use the latest io build, and then install patchwork fresh and give it another shot?

**Comment by clehner** [comment]
With io.js v3.0.0 (npm v2.13.3), chloride and leveldown fail to build:
```
> leveldown@0.10.5 install /usr/local/src/patchwork-iojs/node_modules/scuttlebot/node_modules/secure-scuttlebutt/node_modules/level/node_modules/leveldown
> node-gyp rebuild

make: Entering directory '/usr/local/src/patchwork-iojs/node_modules/scuttlebot/node_modules/secure-scuttlebutt/node_modules/level/node_modules/leveldown/build'
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/db_impl.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/db_iter.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/filename.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/dbformat.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/log_reader.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/log_writer.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/memtable.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/repair.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/table_cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/version_edit.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/version_set.o
../deps/leveldb/leveldb-1.14.0/db/version_set.cc:58:13: warning: ‘std::string leveldb::{anonymous}::IntSetToString(const std::set<long unsigned int>&)’ defined but not used [-Wunused-function]
 std::string IntSetToString(const std::set<uint64_t>& s) {
             ^
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/write_batch.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/helpers/memenv/memenv.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/table/block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/table/block_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/table/filter_block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/table/format.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/table/iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/table/merger.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/table/table.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/table/table_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/table/two_level_iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/arena.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/bloom.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/coding.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/comparator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/crc32c.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/env.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/filter_policy.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/hash.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/logging.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/options.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/status.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/port/port_posix.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/env_posix.o
  AR(target) Release/obj.target/deps/leveldb/leveldb.a
  COPY Release/leveldb.a
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy.o
  AR(target) Release/obj.target/deps/snappy/snappy.a
  COPY Release/snappy.a
  CXX(target) Release/obj.target/leveldown/src/batch.o
In file included from ../src/batch.cc:5:0:
../node_modules/nan/nan.h:261:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../node_modules/nan/nan.h:256:25: note: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../node_modules/nan/nan.h:661:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:661:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:665:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:665:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:672:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:672:67: note: candidates are:
In file included from ../src/batch.cc:2:0:
/home/cel/.node-gyp/3.0.0/include/node/node_buffer.h:35:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Handle<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/cel/.node-gyp/3.0.0/include/node/node_buffer.h:35:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/cel/.node-gyp/3.0.0/include/node/node_buffer.h:47:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/cel/.node-gyp/3.0.0/include/node/node_buffer.h:47:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/batch.cc:5:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:676:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:683:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
leveldown.target.mk:110: recipe for target 'Release/obj.target/leveldown/src/batch.o' failed
make: *** [Release/obj.target/leveldown/src/batch.o] Error 1
make: Leaving directory '/usr/local/src/patchwork-iojs/node_modules/scuttlebot/node_modules/secure-scuttlebutt/node_modules/level/node_modules/leveldown/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/cel/.nvm/versions/io.js/v3.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.0.0-pf2
gyp ERR! command "/home/cel/.nvm/versions/io.js/v3.0.0/bin/iojs" "/home/cel/.nvm/versions/io.js/v3.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/src/patchwork-iojs/node_modules/scuttlebot/node_modules/secure-scuttlebutt/node_modules/level/node_modules/leveldown
gyp ERR! node -v v3.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
```

chloride:
```
> chloride@1.0.20-1 install /usr/local/src/patchwork-iojs/node_modules/ssb-keys/node_modules/chloride
> node-gyp rebuild

make: Entering directory '/usr/local/src/patchwork-iojs/node_modules/ssb-keys/node_modules/chloride/build'
  CC(target) Release/obj.target/libsodium/deps/libsodium/src/libsodium/crypto_aead/chacha20poly1305/sodium/aead_chacha20poly1305.o
  CC(target) Release/obj.target/libsodium/deps/libsodium/src/libsodium/crypto_auth/crypto_auth.o
  CC(target) Release/obj.target/libsodium/deps/libsodium/src/libsodium/crypto_auth/hmacsha256/auth_hmacsha256_api.o
  CC(target)
[...]
  CC(target) Release/obj.target/libsodium/deps/libsodium/src/libsodium/crypto_stream/salsa208/ref/stream_salsa208.o
  CC(target) Release/obj.target/libsodium/deps/libsodium/src/libsodium/crypto_stream/salsa208/ref/xor_salsa208.o
  AR(target) Release/obj.target/deps/sodium.a
  COPY Release/sodium.a
  CXX(target) Release/obj.target/sodium/sodium.o
In file included from ../sodium.cc:17:0:
../node_modules/nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:319:17: note: ‘template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)’ previously declared here
   v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                 ^
../node_modules/nan/nan.h:344:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                           ^
../node_modules/nan/nan.h:334:27: note: ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T>&)’ previously declared here
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:757:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:757:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:761:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:761:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:768:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:768:67: note: candidates are:
In file included from ../sodium.cc:9:0:
/home/cel/.node-gyp/3.0.0/include/node/node_buffer.h:35:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Handle<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/cel/.node-gyp/3.0.0/include/node/node_buffer.h:35:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/cel/.node-gyp/3.0.0/include/node/node_buffer.h:47:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/cel/.node-gyp/3.0.0/include/node/node_buffer.h:47:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../sodium.cc:17:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:772:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:773:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
sodium.target.mk:95: recipe for target 'Release/obj.target/sodium/sodium.o' failed
make: *** [Release/obj.target/sodium/sodium.o] Error 1
make: Leaving directory '/usr/local/src/patchwork-iojs/node_modules/ssb-keys/node_modules/chloride/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/cel/.nvm/versions/io.js/v3.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.0.0-pf2
gyp ERR! command "/home/cel/.nvm/versions/io.js/v3.0.0/bin/iojs" "/home/cel/.nvm/versions/io.js/v3.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/src/patchwork-iojs/node_modules/ssb-keys/node_modules/chloride
gyp ERR! node -v v3.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
```

**Comment by dominictarr** [comment]
@clehner this will work with iojs@2.4

**Comment by clehner** [comment]
Using iojs@2.4, getting error with chloride and leveldown: "gyp_main.py: error: no such option: --no-parallel"

```
> leveldown@0.10.5 install /usr/local/src/patchwork-iojs/node_modules/scuttlebot/node_modules/secure-scuttlebutt/node_modules/level/node_modules/leveldown
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.1
gyp info using node@2.4.0 | linux | x64
gyp http GET https://iojs.org/dist/v2.4.0/iojs-v2.4.0.tar.gz
gyp http 200 https://iojs.org/dist/v2.4.0/iojs-v2.4.0.tar.gz
gyp http GET https://iojs.org/dist/v2.4.0/SHASUMS256.txt
gyp http 200 https://iojs.org/dist/v2.4.0/SHASUMS256.txt
gyp info spawn python2
gyp info spawn args [ '/home/cel/.nvm/versions/io.js/v2.4.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/src/patchwork-iojs/node_modules/scuttlebot/node_modules/secure-scuttlebutt/node_modules/level/node_modules/leveldown/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/cel/.nvm/versions/io.js/v2.4.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/cel/.node-gyp/2.4.0/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/cel/.node-gyp/2.4.0',
gyp info spawn args   '-Dmodule_root_dir=/usr/local/src/patchwork-iojs/node_modules/scuttlebot/node_modules/secure-scuttlebutt/node_modules/level/node_modules/leveldown',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/home/cel/.nvm/versions/io.js/v2.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.0.0-pf2
gyp ERR! command "/home/cel/.nvm/versions/io.js/v2.4.0/bin/iojs" "/home/cel/.nvm/versions/io.js/v2.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/src/patchwork-iojs/node_modules/scuttlebot/node_modules/secure-scuttlebutt/node_modules/level/node_modules/leveldown
gyp ERR! node -v v2.4.0
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm info attempt registry request try #1 at 15:41:17
npm http request GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan
npm info install nan@1.9.0 into /usr/local/src/patchwork-iojs/node_modules/scuttlebot/node_modules/secret-stack/node_modules/secret-handshake/node_modules/chloride
npm info installOne nan@1.9.0
npm info preinstall nan@1.9.0
npm info build /usr/local/src/patchwork-iojs/node_modules/scuttlebot/node_modules/secret-stack/node_modules/secret-handshake/node_modules/chloride/node_modules/nan
npm info linkStuff nan@1.9.0
npm info install nan@1.9.0
npm info postinstall nan@1.9.0
npm info build /usr/local/src/patchwork-iojs/node_modules/scuttlebot/node_modules/secret-stack/node_modules/secret-handshake/node_modules/chloride
npm info linkStuff chloride@1.0.20-1
npm info install chloride@1.0.20-1
npm info leveldown@0.10.5 Failed to exec install script




> chloride@1.0.20-1 install /usr/local/src/patchwork-iojs/node_modules/ssb-keys/node_modules/chloride
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.1
gyp info using node@2.4.0 | linux | x64
gyp info spawn python2
gyp info spawn args [ '/home/cel/.nvm/versions/io.js/v2.4.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/src/patchwork-iojs/node_modules/ssb-keys/node_modules/chloride/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/cel/.nvm/versions/io.js/v2.4.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/cel/.node-gyp/2.4.0/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/cel/.node-gyp/2.4.0',
gyp info spawn args   '-Dmodule_root_dir=/usr/local/src/patchwork-iojs/node_modules/ssb-keys/node_modules/chloride',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/home/cel/.nvm/versions/io.js/v2.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.0.0-pf2
gyp ERR! command "/home/cel/.nvm/versions/io.js/v2.4.0/bin/iojs" "/home/cel/.nvm/versions/io.js/v2.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/src/patchwork-iojs/node_modules/ssb-keys/node_modules/chloride
gyp ERR! node -v v2.4.0
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm info postinstall ws@0.5.0
npm info build /usr/local/src/patchwork-iojs/node_modules/ssb-patchwork-ui/node_modules/ssb-client/node_modules/pull-ws-server
npm info linkStuff pull-ws-server@1.3.4
npm info install pull-ws-server@1.3.4
npm info postinstall pull-ws-server@1.3.4
npm info build /usr/local/src/patchwork-iojs/node_modules/ssb-patchwork-ui/node_modules/ssb-client
npm info linkStuff ssb-client@1.0.2
npm info install ssb-client@1.0.2
npm info postinstall ssb-client@1.0.2
npm info build /usr/local/src/patchwork-iojs/node_modules/ssb-patchwork-ui
npm info linkStuff ssb-patchwork-ui@0.0.10
npm info install ssb-patchwork-ui@0.0.10
npm info postinstall ssb-patchwork-ui@0.0.10
npm info chloride@1.0.20-1 Failed to exec install script
```

**Comment by clehner** [comment]
As of 4fb5789b5002bd587a273ef0a33bc2072b34baab and Node v4.2.1, after removing  ./node_modules and ~/.ssb, I no longer experience any of these errors
