### PR TITLE
Set Windows port correctly

### LINKED ISSUE #969: Stuck "Scuttling..." on 3.11.5 and 3.11.6
Since migrating to 3.11.5 my Patchwork seems to just sit there "Scuttling...".  I then installed 3.11.6 with the same results.

I cloned the repo and built it from source to find this in console:
`git-ssb is not installed, or not available in path`

afaik it should spawn a git-ssb server on its own, correct?  I had an older version installed a couple days ago and it worked fine.

I went ahead and did a manual `npm install git-ssb` and restarted the server to get this exception and stack trace:

```
Error: Cannot find module 'ssb-about'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (D:\git\patchwork\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\git\patchwork\server-process.js:31:8)
    at Object.<anonymous> (D:\git\patchwork\server-process.js:74:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
```

There is also a deprecation notice when installing git-ssb:
```
npm WARN deprecated git-ssb@2.3.6: Installing git-ssb from centralized npm registry is deprecated; use ssb-npm
npm WARN deprecated git-remote-ssb@2.0.4: Installing git-remote-ssb from centralized npm registry is deprecated; use ssb-npm instead
npm WARN deprecated ssb-git-repo@2.8.3: Installing ssb-git-repo from centralized npm registry is deprecated; use ssb-npm instead
npm WARN @staltz/sbot-gossip@1.2.3 requires a peer of scuttlebot@>=11 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
```

I'm not familiar with the ssb-npm toolchain, but maybe this is the root of the issue with booting it on Windows.

### PR DESCRIPTION
**Pull request by christianbundy**
Resolves #969 

cc: @funwhilelost could you test this? I'm feeling good about this one.

### CODE REVIEW

**Comment by funwhilelost** [comment]
Bingo.  Looks good on Windows now:

image
